### ISSUE TITLE
[next-css] Not finding style.css in production

### ISSUE THREAD

**Issue by stramel** [zeit/next-plugins#177]
Attempting to build for production and the styling is failing using `next-css`.

Steps I'm using to test "production" build:

1. `NODE_ENV=production next build`
2. `NODE_ENV=production node server.js`

Here are my config files https://gist.github.com/stramel/bfcf2c8d2572f92a344bfc6247a51f08

This is my server file.
https://gist.github.com/stramel/7f2b66a51b5557d8f5d00f2f4a7078b7

My `index.css` file contains:

```css
@import "normalize.css";
@import "@blueprintjs/core/lib/css/blueprint.css";
@import "@blueprintjs/icons/lib/css/blueprint-icons.css";
@import "leaflet/dist/leaflet.css";
@import "leaflet.pm/dist/leaflet.pm.css";
@import "draft-js/dist/Draft.css";
@import "draft-js-mention-plugin/lib/plugin.css";

a,
a:hover {
  color: inherit;
  text-decoration: inherit;
}

pre {
  background: inherit;
  padding: inherit;
}

.pt-portal {
  display: block;
}

.pt-overlay.pt-overlay-open.pt-overlay-scroll-container,
.pt-transition-container,
.pt-toast-container {
  z-index: 1000;
}

.pt-input {
  border-radius: 4px;
}

/* Style necessary for Leaflet Draw */
.sr-only {
  display: none;
}
```

This is my `_document.js`, `_app.js`, `index.js` file.
https://gist.github.com/stramel/67b76f1c13445709b112f0902a4042d3

Using Next.js v6.0.3 with next-css v0.1.5

I will attempt to create a reproducible repo for you.
