### ISSUE TITLE
next-css plugin doesn't work

### ISSUE THREAD

**Issue by awinogradov** [zeit/next-plugins#268]
So, after:
- `npm install --save @zeit/next-css`
- echo '`const withCSS = require('@zeit/next-css'); module.exports = withCSS();`' > `next.config.js`

`./style.css`
``` css
body {
    background: #000;
}

.Page {
    color: red;
}
```

`./pages/index.js`
``` js
import '../style.css';

export default () => <div className="Page">Welcome to next.js!</div>
```

- `next`

No CSS on the page.
