### ISSUE TITLE
Warning: Prop `className` did not match. Server: "null" Client: "Calendar_header__o6AyK" - using CSS Modules

### ISSUE THREAD

**Issue by maximelebastard** [zeit/next-plugins#619]
**Versions & Environment**

Yarn 1.22.0
next 9.2.2
react 16.13.0
react-dom 16.13.0

**Context**
I'm coding a calendar as a Grid View. The following code describes the Header with the days, but the same bug happens with the body and the rows.

**Code**
MonthHead.tsx
```tsx
import React, { useContext } from "react";
import styles from "../index.module.css"
import { format } from "date-fns";
import { fr } from 'date-fns/locale';
import { CalendarContext } from "..";

console.log({ styles });

const MonthHead: React.FC = () => {
  const { dates } = useContext(CalendarContext);

  const headerDates = dates.slice(0, 7);

  return (<div className={styles.head}>
    {headerDates.map((date) => <div key={date.toISOString()} className={styles.header}>
      {format(date, 'EEEE', { locale: fr })}
    </div>)
    }
  </div >
  )
}

export default MonthHead;
```

index.module.css (truncated)
```css
.head {
  background: white;
  display: flex;
  overflow-y: scroll;
}

.head .header {
  flex: 1 1 auto;
  width: 0;
  border-bottom: 1px solid #bbb;
  border-right: 1px solid #bbb;
  box-sizing: border-box;
}
.monthCalendar .header {
  text-align: center;
  font-weight: 700;
  padding: 8px 0;
}
``` 

**Expected behavior**

To get the right DOM generated for this header, with no error in the console.

**Actual behavior**

Some classes are missing, and I get this error message

```
Warning: Prop `className` did not match. Server: "null" Client: "Calendar_header__o6AyK"
    in div (at MonthHead.tsx:15)
    in div (at MonthHead.tsx:14)
    in MonthHead (at Calendar/index.tsx:71)
    in div (at Calendar/index.tsx:69)
    in div (at Calendar/index.tsx:68)
    in Calendar (at agenda.tsx:44)
    in div (at agenda.tsx:43)
    in main (at agenda.tsx:33)
    in Agenda (at _app.tsx:4)
    in ScoppeProApp
    in Container (created by AppContainer)
    in AppContainer
```
