### ISSUE TITLE
@font-face removed in output

### ISSUE THREAD

**Issue by ghengeveld** [zeit/next-plugins#89]
Given the following stylesheet:

```css
@font-face {
  font-family: "Akkurat";
  src: url("/static/fonts/akkurat_regular.woff") format("woff");
  font-weight: normal;
  font-style: normal;
  font-display: fallback;
}

html,
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
}
```

Contents of `.next/static/style.css` / `/_next/static/style.css`:

```css
body,html{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen-Sans,Ubuntu,Cantarell,Helvetica Neue,sans-serif}
/*# sourceMappingURL=style.css.map*/
```

Seems like the entire `@font-face` block is stripped from the result.

I'm hoping this will be resolved with #10, but I'm putting this out there so it won't be overlooked.
